@uri = https://localhost:5001

@bookingsuri = {{uri}}/api/bookings

###

GET {{bookingsuri}}

###

POST {{bookingsuri}}
Content-Type: application/json

{
    "RoomId": 1,
    "IsActive": true,
    "StartDate": "2021-07-17T00:00:00Z",
    "EndDate": "2021-07-16T00:00:00Z",
    "Description": "This is the new room"
}

###

GET {{bookingsuri}}/2


###

PUT {{bookingsuri}}/2
Content-Type: application/json

{
    "id": 2,
    "roomId": 2
}

###

DELETE {{bookingsuri}}/2